-- ==========================================================================
-- Glamor Sutil - Supabase Setup Script
-- Paste this script into the Supabase SQL Editor (https://supabase.com)
-- ==========================================================================

-- 1. Create Categories Table
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  description TEXT,
  image_url TEXT NOT NULL,
  category_id BIGINT REFERENCES categories(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies for Categories
CREATE POLICY "Allow public read access to categories" 
ON categories FOR SELECT USING (true);

CREATE POLICY "Allow write access only to admin email on categories"
ON categories FOR ALL TO authenticated
USING (auth.jwt() ->> 'email' = 'admin@glamorsutil.com')
WITH CHECK (auth.jwt() ->> 'email' = 'admin@glamorsutil.com');

-- 5. Create RLS Policies for Products
CREATE POLICY "Allow public read access to products" 
ON products FOR SELECT USING (true);

CREATE POLICY "Allow write access only to admin email on products"
ON products FOR ALL TO authenticated
USING (auth.jwt() ->> 'email' = 'admin@glamorsutil.com')
WITH CHECK (auth.jwt() ->> 'email' = 'admin@glamorsutil.com');

-- 6. Configure Supabase Storage Bucket for Product Media
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-media', 'product-media', true)
ON CONFLICT (id) DO NOTHING;

-- 7. Storage RLS Policies
CREATE POLICY "Allow public read access to product-media"
ON storage.objects FOR SELECT
USING ( bucket_id = 'product-media' );

CREATE POLICY "Allow admin upload access to product-media"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'product-media' );

CREATE POLICY "Allow admin delete access to product-media"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'product-media' );
